/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/cheese.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[0, -Math.PI / 2, 0]}>
        <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
        <mesh geometry={nodes.mesh_0_1.geometry} material={nodes.mesh_0_1.material} />
        <mesh geometry={nodes.mesh_0_2.geometry} material={nodes.mesh_0_2.material} />
      </group>
      <group rotation={[-Math.PI, -Math.PI / 3, -Math.PI]}>
        <mesh geometry={nodes.mesh_1.geometry} material={nodes.mesh_1.material} />
        <mesh geometry={nodes.mesh_1_1.geometry} material={nodes.mesh_1_1.material} />
        <mesh geometry={nodes.mesh_1_2.geometry} material={nodes.mesh_1_2.material} />
      </group>
      <group rotation={[-Math.PI, -Math.PI / 6, -Math.PI]}>
        <mesh geometry={nodes.mesh_2.geometry} material={nodes.mesh_2.material} />
        <mesh geometry={nodes.mesh_2_1.geometry} material={nodes.mesh_2_1.material} />
        <mesh geometry={nodes.mesh_2_2.geometry} material={nodes.mesh_2_2.material} />
      </group>
      <group rotation={[0, Math.PI / 3, 0]}>
        <mesh geometry={nodes.mesh_3.geometry} material={nodes.mesh_3.material} />
        <mesh geometry={nodes.mesh_3_1.geometry} material={nodes.mesh_3_1.material} />
        <mesh geometry={nodes.mesh_3_2.geometry} material={nodes.mesh_3_2.material} />
      </group>
      <group rotation={[-Math.PI, Math.PI / 3, -Math.PI]}>
        <mesh geometry={nodes.mesh_4.geometry} material={nodes.mesh_4.material} />
        <mesh geometry={nodes.mesh_4_1.geometry} material={nodes.mesh_4_1.material} />
        <mesh geometry={nodes.mesh_4_2.geometry} material={nodes.mesh_4_2.material} />
      </group>
      <group rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.mesh_5.geometry} material={nodes.mesh_5.material} />
        <mesh geometry={nodes.mesh_5_1.geometry} material={nodes.mesh_5_1.material} />
        <mesh geometry={nodes.mesh_5_2.geometry} material={nodes.mesh_5_2.material} />
      </group>
      <group rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.mesh_6.geometry} material={nodes.mesh_6.material} />
        <mesh geometry={nodes.mesh_6_1.geometry} material={nodes.mesh_6_1.material} />
        <mesh geometry={nodes.mesh_6_2.geometry} material={nodes.mesh_6_2.material} />
      </group>
      <group rotation={[0, -Math.PI / 6, 0]}>
        <mesh geometry={nodes.mesh_8.geometry} material={nodes.mesh_8.material} />
        <mesh geometry={nodes.mesh_8_1.geometry} material={nodes.mesh_8_1.material} />
        <mesh geometry={nodes.mesh_8_2.geometry} material={nodes.mesh_8_2.material} />
      </group>
      <group rotation={[0, -Math.PI / 3, 0]}>
        <mesh geometry={nodes.mesh_9.geometry} material={nodes.mesh_9.material} />
        <mesh geometry={nodes.mesh_9_1.geometry} material={nodes.mesh_9_1.material} />
        <mesh geometry={nodes.mesh_9_2.geometry} material={nodes.mesh_9_2.material} />
      </group>
      <group rotation={[-Math.PI, Math.PI / 6, -Math.PI]}>
        <mesh geometry={nodes.mesh_10.geometry} material={nodes.mesh_10.material} />
        <mesh geometry={nodes.mesh_10_1.geometry} material={nodes.mesh_10_1.material} />
        <mesh geometry={nodes.mesh_10_2.geometry} material={nodes.mesh_10_2.material} />
      </group>
      <group rotation={[0, Math.PI / 6, 0]}>
        <mesh geometry={nodes.mesh_7.geometry} material={nodes.mesh_7.material} />
        <mesh geometry={nodes.mesh_7_1.geometry} material={nodes.mesh_7_1.material} />
        <mesh geometry={nodes.mesh_7_2.geometry} material={nodes.mesh_7_2.material} />
      </group>
      <mesh geometry={nodes.mesh_11.geometry} material={nodes.mesh_11.material} />
      <mesh geometry={nodes.mesh_11_1.geometry} material={nodes.mesh_11_1.material} />
      <mesh geometry={nodes.mesh_11_2.geometry} material={nodes.mesh_11_2.material} />
    </group>
  )
}

useGLTF.preload('/models/cheese.gltf')
