/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/coin.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-1, 0, 0.5]}>
        <mesh geometry={nodes.mesh_0.geometry} material={materials.gold} />
        <mesh geometry={nodes.mesh_0_1.geometry} material={materials.wood} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/coin.gltf')
