/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/race.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 0.1, 0]}>
        <mesh geometry={nodes.Mesh_body.geometry} material={materials.paintRed} />
        <mesh geometry={nodes.Mesh_body_1.geometry} material={nodes.Mesh_body_1.material} />
        <mesh geometry={nodes.Mesh_body_2.geometry} material={materials.window} />
        <mesh geometry={nodes.Mesh_body_3.geometry} material={materials._defaultMat} />
      </group>
      <group position={[-0.35, 0.3, 0.88]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.Mesh_wheel_frontLeft.geometry} material={nodes.Mesh_wheel_frontLeft.material} />
        <mesh geometry={nodes.Mesh_wheel_frontLeft_1.geometry} material={nodes.Mesh_wheel_frontLeft_1.material} />
        <mesh geometry={nodes.Mesh_wheel_frontLeft_2.geometry} material={nodes.Mesh_wheel_frontLeft_2.material} />
      </group>
      <group position={[0.35, 0.3, 0.88]}>
        <mesh geometry={nodes.Mesh_wheel_frontLeft.geometry} material={nodes.Mesh_wheel_frontLeft.material} />
        <mesh geometry={nodes.Mesh_wheel_frontLeft_1.geometry} material={nodes.Mesh_wheel_frontLeft_1.material} />
        <mesh geometry={nodes.Mesh_wheel_frontLeft_2.geometry} material={nodes.Mesh_wheel_frontLeft_2.material} />
      </group>
      <group position={[-0.35, 0.3, -0.64]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.Mesh_wheel_frontLeft.geometry} material={nodes.Mesh_wheel_frontLeft.material} />
        <mesh geometry={nodes.Mesh_wheel_frontLeft_1.geometry} material={nodes.Mesh_wheel_frontLeft_1.material} />
        <mesh geometry={nodes.Mesh_wheel_frontLeft_2.geometry} material={nodes.Mesh_wheel_frontLeft_2.material} />
      </group>
      <group position={[0.35, 0.3, -0.64]}>
        <mesh geometry={nodes.Mesh_wheel_frontLeft.geometry} material={nodes.Mesh_wheel_frontLeft.material} />
        <mesh geometry={nodes.Mesh_wheel_frontLeft_1.geometry} material={nodes.Mesh_wheel_frontLeft_1.material} />
        <mesh geometry={nodes.Mesh_wheel_frontLeft_2.geometry} material={nodes.Mesh_wheel_frontLeft_2.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/race.glb')
