/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/taxi.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 0.2, -0.1]}>
        <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
        <mesh geometry={nodes.mesh_0_1.geometry} material={materials.paintYellow} />
        <mesh geometry={nodes.mesh_0_2.geometry} material={materials.lightFront} />
        <mesh geometry={nodes.mesh_0_3.geometry} material={materials._defaultMat} />
        <mesh geometry={nodes.mesh_0_4.geometry} material={materials.window} />
        <mesh geometry={nodes.mesh_0_5.geometry} material={materials.lightBack} />
      </group>
      <group position={[-0.35, 0.3, 0.76]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.mesh_1.geometry} material={nodes.mesh_1.material} />
        <mesh geometry={nodes.mesh_1_1.geometry} material={nodes.mesh_1_1.material} />
      </group>
      <group position={[0.35, 0.3, 0.76]}>
        <mesh geometry={nodes.mesh_2.geometry} material={nodes.mesh_2.material} />
        <mesh geometry={nodes.mesh_2_1.geometry} material={nodes.mesh_2_1.material} />
      </group>
      <group position={[-0.35, 0.3, -0.76]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.mesh_3.geometry} material={nodes.mesh_3.material} />
        <mesh geometry={nodes.mesh_3_1.geometry} material={nodes.mesh_3_1.material} />
      </group>
      <group position={[0.35, 0.3, -0.76]}>
        <mesh geometry={nodes.mesh_4.geometry} material={nodes.mesh_4.material} />
        <mesh geometry={nodes.mesh_4_1.geometry} material={nodes.mesh_4_1.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/taxi.gltf')
