/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/tractor.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 0.17, -0.04]} scale={1.12}>
        <mesh geometry={nodes.mesh_0.geometry} material={materials.paintBlue} />
        <mesh geometry={nodes.mesh_0_1.geometry} material={materials.window} />
        <mesh geometry={nodes.mesh_0_2.geometry} material={nodes.mesh_0_2.material} />
        <mesh geometry={nodes.mesh_0_3.geometry} material={materials.lightFront} />
        <mesh geometry={nodes.mesh_0_4.geometry} material={materials._defaultMat} />
      </group>
      <mesh
        geometry={nodes.skirts.geometry}
        material={nodes.skirts.material}
        position={[-0.5, 0.28, 1.17]}
        scale={1.12}
      />
      <group position={[-0.39, 0.44, 0.4]} scale={[-1.46, 1.46, 1.46]}>
        <mesh geometry={nodes.mesh_2.geometry} material={nodes.mesh_2.material} />
        <mesh geometry={nodes.mesh_2_1.geometry} material={nodes.mesh_2_1.material} />
        <mesh geometry={nodes.mesh_2_2.geometry} material={nodes.mesh_2_2.material} />
      </group>
      <group position={[0.39, 0.44, 0.4]} scale={1.46}>
        <mesh geometry={nodes.mesh_3.geometry} material={nodes.mesh_3.material} />
        <mesh geometry={nodes.mesh_3_1.geometry} material={nodes.mesh_3_1.material} />
        <mesh geometry={nodes.mesh_3_2.geometry} material={nodes.mesh_3_2.material} />
      </group>
      <group position={[-0.39, 0.27, -0.6]} scale={[-0.9, 0.9, 0.9]}>
        <mesh geometry={nodes.mesh_4.geometry} material={nodes.mesh_4.material} />
        <mesh geometry={nodes.mesh_4_1.geometry} material={nodes.mesh_4_1.material} />
      </group>
      <group position={[0.39, 0.27, -0.6]} scale={0.9}>
        <mesh geometry={nodes.mesh_5.geometry} material={nodes.mesh_5.material} />
        <mesh geometry={nodes.mesh_5_1.geometry} material={nodes.mesh_5_1.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/tractor.gltf')
